### ISSUE TITLE
Embed lyrics

### ISSUE THREAD

**Issue by iJahangard** [Lambada10/SongSync#10]
I have a plenty of beautiful songs
Having lots of lrc files just don't what I want as I'm searching for something that i can embed lrc files to my audio files (mp3,flac etc.)

**Comment by iJahangard** [comment]
It would be great as you find lyrics simply embed them to song with just a click

The app should have a sorting system as you download new song you'll see them at the top of other songs,then embedize new songs will be so much easier

**Comment by BhaturaGuy** [comment]
+1

**Comment by peter9811** [comment]
+1

**Comment by okgamr** [comment]
Uhm, you can use Oto Music or Gramophone (there may be more music players that have this feature so choose the one you like) to view the lyrics while listening to your beautiful music. These apps have the lyrics feature implemented into them and SongSync automatically embeds the lyrics in the file so technically you just need to save the lyrics for a song, reach the music player, play a song which you have downloaded the lyrics, then press the button that shows lyrics - ta-da! the lyrics for your specific song show up and you can finally read them while you listen to the song!

**Comment by nift4** [comment]
@ThreeDeeJay Embedded lyrics can be synced, and SongSync does currently not embed lyrics

**Comment by ThreeDeeJay** [comment]
Oh, neat. You're right. Both the players I mentioned indeed read synced embedded lyrics properly.
I must've had some outdated information from last I checked a long time ago when there was little adoption, like PlayerPro, which still shows embedded lyrics' timestamps though fwiw it doesn't support LRC to begin with.
