### ISSUE TITLE
Spotify Rate Limit

### ISSUE THREAD

**Issue by rjm831** [Lambada10/SongSync#100]
I realize its the Spotify api and not a bug but it just started recently and is really a pain - I have a large music library.  Is there any workaround to solve this rate limit issue?

**Comment by Lambada10** [comment]
@rjm831 Musixmatch is a good alternative as Spotify uses their database as well, you can get the latest GitHub Actions build and use Musixmatch source as a workaround

**Comment by rjm831** [comment]
After experimenting a bit I've come to suspect the reason I'm getting rate limited so quickly is because I have Google heavily blocked on my NextDNS.  Issue closed; sorry for the post.
PS really appreciate thegreat app.  Thank you all!

**Comment by chishxd** [comment]
I changed the provider to Musixmatch, But I still get the same error. And I've double checked I don't use any DNS as well. How can I fix it?

**Comment by Lambada10** [comment]
@chishxd Musixmatch is broken right now

**Comment by chishxd** [comment]
> @chishxd Musixmatch is broken right now

So, which one should I use?
