### ISSUE TITLE
Word by word lyric not supported

### ISSUE THREAD

**Issue by anonymouseferb** [Lambada10/SongSync#101]
I liked @Lambada10 when it had no word by word lyric support, right now all lyrics are shown as word by word, and not the normal synced lyrics. Our music players don't support word by word, right now I'm using Musicolet. Please try fix this and I'll appreciate your help to all music lovers

**Comment by Lambada10** [comment]
Only Apple Music has word by word lyrics, use any other provider to get normal synced lyrics
