### ISSUE TITLE
Bulk download lyrics bug.

### ISSUE THREAD

**Issue by Rachitidk** [Lambada10/SongSync#110]
Bulk download save lrc instead embedded lyrics.

**Comment by Lambada10** [comment]
@Rachitidk Are you sure you don't have embed lyrics checkbox marked?

**Comment by Rachitidk** [comment]
Oh sorry, I meant the opposite it save as lrc fire instead of embed lyrics.

**Comment by U-alb** [comment]
I also have this issue. The embed lyrics to file checkbox is marked, yet it saves separate .lrc files

Is there any way I could help? Logs or other such information

**Comment by U-alb** [comment]
This may be useful information: manually embedding lyrics to files (1 by 1) works correctly. 

Only batch downloading with the _Embed lyrics to file_ box checked has the issue of saving them as a separate .lrc file regardless
