### ISSUE TITLE
Apple music lyrics error in some song.

### ISSUE THREAD

**Issue by Rachitidk** [Lambada10/SongSync#111]
https://github.com/user-attachments/assets/2573c346-8050-482e-9ae2-408d2eeca759

**Comment by Rachitidk** [comment]
https://github.com/user-attachments/assets/c178941a-bd2c-412b-bf21-d2db9a90603b

In this song it give correct lyrics. Also even whole name and artist is same, something it will show different song and have to try again to change.

**Comment by Lambada10** [comment]
Use "edit" button to adjust the search query, nothing can be done on my side about it

**Comment by Rachitidk** [comment]
@Lambada10 did you check the video, that was secondary problem mentioned, they primary problem is with lyrics multiple times check the video properly.
Thanks you.
Best regards.

**Comment by Lambada10** [comment]
I'm not sure what do you mean
Are you talking about A2 extension (word-by-word lyrics)? 
```
[00:00.00] <00:00.04> This <00:00.16> is <00:00.82> an <00:01.29> example <00:01.63> of <00:03.09> a2 <00:03.37> lrc <00:05.92> extension
```
If so, it's expected behavior to get these lyrics from apple music

**Comment by Rachitidk** [comment]
[Bhai Hai_Fotty Seven.zip](https://github.com/user-attachments/files/17871785/Bhai.Hai_Fotty.Seven.zip)
Here's the song, try to download the lyrics for it from apple music.

**Comment by Lambada10** [comment]
The lyrics are there
What is your desired effect?

**Comment by Rachitidk** [comment]
Biroooooo, did you even try to add lyrics to song provided/ saw the first video. Check this completely please.
This is how lyrics is displayed.
![1000114279](https://github.com/user-attachments/assets/d3a2d638-d439-4a56-bcca-3ccb5c4fc811)
This is how it should be{by musicxmatch(and I am not talking about translation}.
![1000114278](https://github.com/user-attachments/assets/88f5b5b2-923a-46dc-80b9-870a80a25d8e).
@Lambada10

**Comment by nift4** [comment]
@Rachitidk This is because your music player does not support word-by-word timestamp. Using a music player that supports it will result in proper display, and word-by-word animation. Or, if you don't want to change your music player, you can use another provider

**Comment by Rachitidk** [comment]
> @Rachitidk This is because your music player does not support word-by-word timestamp. Using a music player that supports it will result in proper display, and word-by-word animation. Or, if you don't want to change your music player, you can use another provider

Suggest a music player, I will try.

**Comment by Rachitidk** [comment]
@Lambada10 Thanks for clearingy queries, I was unaware of it. Can you please suggest a music player to use.

**Comment by ThreeDeeJay** [comment]
@DepressedDeity I found just one, which was taken down from Google Play for some reason: [Medoly](https://apkpure.com/medoly/com.wa2c.android.medoly/downloading) with its [LRC plugin](https://apkpure.com/medoly-lrc-lyrics-plugin/com.wa2c.android.medoly.plugin.action.lrclyrics/downloading)

![Image](https://github.com/user-attachments/assets/e1d4a124-46ed-4ef5-99f4-be2110b30eee)

Someone on Reddit mentioned PowerAmp could do it but doesn't look like it:

![Image](https://github.com/user-attachments/assets/f6eab758-d1b2-40ff-8846-5c1106229c4e)

I just emailed the Musicolet dev about supporting [Enhanced LRC](https://en.wikipedia.org/wiki/LRC_(file_format)#A2_extension_(Enhanced_LRC_format)) but I ain't getting my hopes up, given it hasn't been updated in nearly a year. 😔

**Comment by nift4** [comment]
https://nightly.link/AkaneTan/Gramophone/actions/runs/15020437728/Gramophone-1.0.16.1.caabb02-release.zip

Gramophone beta builds also support it if you enable new parser & UI in Experimental settings
