### ISSUE TITLE
Please add the translations for Spanish

### ISSUE THREAD

**Issue by woskkdmsosid** [Lambada10/SongSync#113]
Hello, I've recently downloaded the app since there was songs which i couldnt get the lyrics and since i got this app i filled them all in. Thanks for making this app!! 

Back to rhe problem, I'm a native spanish speaker and have the app in spanish, but there are translations missing in the app! Could they get added please?
![Screenshot_2024-11-22-18-17-33-897_pl lambada songsync](https://github.com/user-attachments/assets/9d8d9ef2-0cb6-4fea-a76e-0c398edd6c12)

**Comment by Lambada10** [comment]
You can translate the app yourself here: https://hosted.weblate.org/engage/songsync/

**Comment by Lambada10** [comment]
Actually looking at the website it's already fully translated, so it will be available in next release, alternatively you could get the latest Github Actions build
