### ISSUE TITLE
Lyrics from apple music appear with extra nonsense character "v1:"

### ISSUE THREAD

**Issue by Nick-DL** [Lambada10/SongSync#127]
**Describe the bug**
see the screenshot.

**To Reproduce**

**Expected behavior**
Always happens

**Screenshots**
![Screenshot_20241221_010408_pl.lambada.songsync.jpg](https://github.com/user-attachments/assets/ab43924a-f9a3-4131-a3b3-d4775bc84b12)

**Smartphone (please complete the following information):**
 - Device: huawei phone
 - OS: harmonyos 3 android 12
 - App version latest

**Additional context**

**Comment by nift4** [comment]
@Nick-DL That's not nonsense, and if you don't like it, you can turn it (multiple person lrc extension) off in SongSync settings

**Comment by Nick-DL** [comment]
OK, thanks!
