### ISSUE TITLE
Adjust lyrics speed

### ISSUE THREAD

**Issue by Jay-Omega-Aston** [Lambada10/SongSync#14]
@Lambada10 I was wondering if its possible for you to add a feature that allows you to adjust the speed in which a lyric sync with songs, like exponentially increasing or decreasing the delay between each line of a lyric.
 I think this would be really useful in applying synced lyrics to slowed and sped up versions of different song, because alot songs sounds better woth their sped or slowed counterparts
An adjusting slider/meter would be preferred or a preset or however you do it, I don't mind. I just think it would be a pretty nice feature to implement

**Comment by Lambada10** [comment]
@Jay-Omega-Aston I don't think I'll ever implement this. SongSync is a lyrics downloader app, not an editor. That idea wouldn't really work out.
