### ISSUE TITLE
Download Failed To Fetch Lyrics

### ISSUE THREAD

**Issue by HonestAbe7** [Lambada10/SongSync#15]
I really appreciate an app that downloads the lyrics of songs on our device. 

So I just went through the scan and all of my music except 2 songs were successful. I checked and couldn't find the 2 successful ones too.

Is there a way to pick where the lyrics are taken from? I don't see any settings for this. 

Looking forward to a working version of this where I can save all my music lyrics offline. 

Thanks

**Comment by Lambada10** [comment]
@HonestAbe7 Everything works fine on my side.
Can you share more details? What does it show, for what music etc..

**Comment by HonestAbe7** [comment]
![Screenshot_20230802-192151](https://github.com/Lambada10/SongSync/assets/88217236/78076109-5eaf-4e9a-aabd-f645d05e30a4)

Here is a screenshot showing the scan in progress. I mainly listen to religious artists if this makes a difference. Thanks

**Comment by Lambada10** [comment]
Are you using Android 10 or below? And are your songs on external storage (SD card)? If so, we can't save to external storage on legacy devices and it counts as  failed
https://github.com/Lambada10/SongSync/commit/133fbb46e460851ff7ae4c2a800b2cd3c90039eb

**Comment by HonestAbe7** [comment]
I am using Android 10 and yes I use an SD card to store my music.

**Comment by HonestAbe7** [comment]
Actually, it did try to save it to the downloads section. Just was an empty directory.

**Comment by Lambada10** [comment]
@HonestAbe7 From browse tab? It should show you the info about cant save and a button to save to downloads instead, you saved it and it didn't save there?

**Comment by HonestAbe7** [comment]
I am talking about when it scans. Nothing I see in the "Browse" tab to specify where except the song name and artist name.

**Comment by HonestAbe7** [comment]
Now it will not scan at all:

![Screenshot_20230803-111925](https://github.com/Lambada10/SongSync/assets/88217236/30dbd59a-f750-4cc5-8c34-b0b3606da9fb)

**Comment by Lambada10** [comment]
@HonestAbe7 Yeah my API key is rate limited right now because many users tried to use the app right now and Spotify doesn't like high traffic

**Comment by HonestAbe7** [comment]
Here is screenshot of the downloads folder I was talking about on the device 

![Screenshot_20230803-112140](https://github.com/Lambada10/SongSync/assets/88217236/3badfb24-665f-470c-8fce-28ac529f89c7)

**Comment by Lambada10** [comment]
@HonestAbe7 If you never downloaded lyrics for a specific song it's expected to be empty

**Comment by HonestAbe7** [comment]
I just pressed on a song and all it did was highlight it I said yes and failed again.

**Comment by HonestAbe7** [comment]
Can you switch servers or where you get the song info? I know that FastLyrics on F-Droid fetches from Genius site. It just just saved for each song I play and saves it internally hidden to where you can't transfer if you switch devices.
