### ISSUE TITLE
Batch Download immediately gets rate limited and aborts

### ISSUE THREAD

**Issue by Enovale** [Lambada10/SongSync#16]
**Describe the bug**
When using the Batch Download feature, it downloads about 4 songs and then tells me it's reached Spotify's rate limit and stops. I don't see any way to adjust the speed at which it downloads the songs to avoid hitting the rate limit or let it retry. 

**To Reproduce**
1. Open the app, which shows you the home page.
2. Click on 'Batch download lyrics'.
3. Let it download for about 4 songs.
4. See 'Spotify rate limit reached. Please try again later'.

**Expected behavior**
My lyrics get downloaded, and are retried if they hit the rate limit and back off the speed until there are no issues

**Screenshots**
![IMG_20230803_061334](https://github.com/Lambada10/SongSync/assets/17408285/bf552619-5092-404d-8970-575975c3a1de)

**Smartphone (please complete the following information):**
 - Device: [Google Pixel 4a]
 - OS: [GrapheneOS v2023072600]
 - App version [2.1.0]

**Additional context**
My library has 6k songs. This happened the very first time I tried downloading any lyrics.

**Comment by AkaneTan** [comment]
@Enovale That's because songsync is using lambada10's public API and there's a limit. I would suggest wait for a day or compile your own package with your own API.

**Comment by Enovale** [comment]
Sure, but if I set it up with my own API it's just going to eventually rate limit itself anyway (especially with 6k songs). Without any way to back off the API requests it won't be consistent.

**Comment by Lambada10** [comment]
@Enovale What do you mean by "back off the API requests"
Btw when API limit passes, you can filter songs to show no lyrics only and technically continue downloading

**Comment by Enovale** [comment]
> @Enovale What do you mean by "back off the API requests"
If the application is hitting the rate limit it needs to slow down future requests so that in the future it doesn't hit the limit, this is described in Spotify's API usage documentation iirc.

> Btw when API limit passes, you can filter songs to show no lyrics only and technically continue downloading
This would not have worked at all at the time this issue was created because I'm not going to download lyrics *4* songs at a time. However the new update that adds the Web Player API gets rate limited much much later (500 songs or so...?) so I will do this for the time being
