### ISSUE TITLE
App can't find lyrics sometimes

### ISSUE THREAD

**Issue by blwckcore** [Lambada10/SongSync#19]
**Describe the bug**
App throws error, when trying to find a lyrics for song. But sometimes it randomly finds lyrics.

**To Reproduce**
Just search for any song in "Browse" label. Or select any song from library.

**Expected behavior**
App should find the lyrics.

**Screenshots**
![Screenshot_2023-08-03-19-35-22-503_pl lambada songsync](https://github.com/Lambada10/SongSync/assets/107321994/f2662703-c717-41e3-a646-8a0b2c538ca2)

**Smartphone (please complete the following information):**
 - Device: Poco X3 Pro
 - OS: MIUI 13 (Android 12)
 - App version 2.1.0

**Additional context**
I'm from Russia and Spotify requires login to work there. I still have tried to search lyrics with VPN, it worked somehow for once, but next attempts failed.

**Comment by Lambada10** [comment]
@blwckcore My API key is currently limited by Spotify because too many users use the app right now, I'm working on it. Try again later

**Comment by blwckcore** [comment]
oh, ok
