### ISSUE TITLE
App requires internet access 

### ISSUE THREAD

**Issue by Turhvjbufv** [Lambada10/SongSync#22]
**Describe the bug**
I wanna go inside the app but I can't cause the app says I have no connection
**To Reproduce**
Open the app
**Expected behavior**
Opens the app but won't allow you to download or search for lyrics since you have no internet (instead the app closes with a message that you have no internet or Spotify is down)
**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Samsung Galaxy S10, Poco X3 Pro]
 - OS: [e.g. MIUI 13 (Android 12), Pixel Experience 13]
 - App version [e.g. v1.3]

**Additional context**

**Comment by Lambada10** [comment]
@Turhvjbufv Try cleaning app data
