### ISSUE TITLE
possibility to search by approximate names

### ISSUE THREAD

**Issue by Wjxfi** [Lambada10/SongSync#25]
If you can't find lyrics by exact names the possibility to search by approximate names. That is, not "waste" but "Wast3", or not "gangnam style remix zyzy" but "gangnam style ^-^remix^-^ by ZyZy!!!!!". or just, not "come on", but "come on!"

it's useful when I have a lot of remixes, but different sources spell them differently, or their lyrics match the original.

**Comment by Lambada10** [comment]
When you click the track, there's a button "edit" which lets you adjust the query
