### ISSUE TITLE
Ability to write to external storage, embed lyrics and browse to a music folder.

### ISSUE THREAD

**Issue by kcryptonian** [Lambada10/SongSync#28]
![Screenshot_20230806-102803](https://github.com/Lambada10/SongSync/assets/64187248/cc2bb62a-55e3-4fdc-9c9e-88fa6bb23116)

1. Please enable support for saving lyrics file into into external storage, as I (and I'm sure many others as well) have their music files stored in SD card. (My phone is android 9)

2. Add options to embedd lyrics directly into the music file in addition to the ".lrc" option. In that way, one wouldn't have to copy the browsed lyrics to go and manually embed in the music.

3. Add option to actually browse and select a particular local folder in which the songs are.  Having to go through "ignore" folders could be an headache especially when you have tons of subfolder (including those under internal storage and external storage) where musics are located and grouped as either different playlists, albums etc

4. Black/Dark theme appearance option pleaseeeee! :)

Great Job dev, keep it up. 
An app like yours is what I've been looking for for a while now to complement my musicolet app. I'm sure many musicolet users also share my sentiments. Your app could be the next big thing in the "SYNCED" offline lyrics niche just as musicolet has been for the offline music niche.

**Comment by Lambada10** [comment]
@kcryptonian 1. It works on Android 11+
2. Will need to find a tool for that, also if you choose a song item it'll redirect you to the browse tab, but will save the file in the same file path as music is saved. (Assuming you're using Android 11+)
3. A search feature exists, just search for a song you're looking for
4. Dark theme is a thing and it should turn on automatically based on your system theme

**Comment by zerobun** [comment]
Just came here to request for the lyrics embed feature currently I manually embed the lyrics using an app called synced lyrics (https://play.google.com/store/apps/details?id=lyriceditor.lyricsearch.embedlyrictomp3.syncedlyriceditor&hl=en_US&referrer=utm_source%3Dgoogle%26utm_medium%3Dorganic%26utm_term%3Dsynced+lyrics+editor&pcampaignid=APPU_1_SkLQZNvpEK_kseMPh7Sy6Ao)
It just embeds the lyrics you past or you can get the lyrics from a .irc file too.

**Comment by nezhnyy** [comment]
> Just came here to request for the lyrics embed feature currently I manually embed the lyrics using an app called [Synced Lyrics editor](https://play.google.com/store/apps/details?id=lyriceditor.lyricsearch.embedlyrictomp3.syncedlyriceditor&hl=en_US&referrer=utm_source%3Dgoogle%26utm_medium%3Dorganic%26utm_term%3Dsynced+lyrics+editor&pcampaignid=APPU_1_SkLQZNvpEK_kseMPh7Sy6Ao) It just embeds the lyrics into the song file, which you can paste or you can get the lyrics from a .irc file too.

I use [this](https://github.com/yogeshwaran01/lyricy) to embed lyrics in batches via termux, my command :
```
$ cd /your/music/path/
$ find . -name "*.lrc" -exec lyricy add --lrc {} {}.mp3 \;
```
nb. 
* lrc & mp3 must be in the same directory & same file name
* you need to add the suffix .lrc to the mp3 file, ex: mymusic.lrc.mp3
* use mixplorer to rename in batch




> @kcryptonian 1. It works on Android 11+ 2. Will need to find a tool for that, also if you choose a song item it'll redirect you to the browse tab, but will save the file in the same file path as music is saved. (Assuming you're using Android 11+) 3. A search feature exists, just search for a song you're looking for 4. Dark theme is a thing and it should turn on automatically based on your system theme

check this https://github.com/yogeshwaran01/lyricy

**Comment by kcryptonian** [comment]
> @kcryptonian 1. It works on Android 11+ 2. Will need to find a tool for that, also if you choose a song item it'll redirect you to the browse tab, but will save the file in the same file path as music is saved. (Assuming you're using Android 11+) 3. A search feature exists, just search for a song you're looking for 4. Dark theme is a thing and it should turn on automatically based on your system theme

Unfortunately, my android 9 doesn't have the syten dark theme feature. It wouldn't hurt to include the feature dev ):

**Comment by kcryptonian** [comment]
> > Just came here to request for the lyrics embed feature currently I manually embed the lyrics using an app called [Synced Lyrics editor](https://play.google.com/store/apps/details?id=lyriceditor.lyricsearch.embedlyrictomp3.syncedlyriceditor&hl=en_US&referrer=utm_source%3Dgoogle%26utm_medium%3Dorganic%26utm_term%3Dsynced+lyrics+editor&pcampaignid=APPU_1_SkLQZNvpEK_kseMPh7Sy6Ao) It just embeds the lyrics into the song file, which you can paste or you can get the lyrics from a .irc file too.
> 
> I use [this](https://github.com/yogeshwaran01/lyricy) to embed lyrics in batches via termux, my command :
> 
> ```
> $ cd /your/music/path/
> $ find . -name "*.lrc" -exec lyricy add --lrc {} {}.mp3 \;
> ```
> 
> nb.
> 
> * lrc & mp3 must be in the same directory & same file name
> * you need to add the suffix .lrc to the mp3 file, ex: mymusic.lrc.mp3
> * use mixplorer to rename in batch
> 
> > @kcryptonian 1. It works on Android 11+ 2. Will need to find a tool for that, also if you choose a song item it'll redirect you to the browse tab, but will save the file in the same file path as music is saved. (Assuming you're using Android 11+) 3. A search feature exists, just search for a song you're looking for 4. Dark theme is a thing and it should turn on automatically based on your system theme
> 
> check this https://github.com/yogeshwaran01/lyricy

I'll, thanks.
