### ISSUE TITLE
Downloads wrong lyrics

### ISSUE THREAD

**Issue by yavko** [Lambada10/SongSync#29]
**Describe the bug**

Sometimes it's a completely different song's lyrics, sometimes it's from the same album but wrong file name

**To Reproduce**
1. Batch download
2. See error

**Expected behavior**

Correct lyrics

**Screenshots**

![Screenshot_20230807-134240_Material Files.png](https://github.com/Lambada10/SongSync/assets/15178513/6eb93f20-b3bf-4994-ad19-4d27aa2d372d)
> Song from same album but with wrong filename

**Smartphone (please complete the following information):**
 - Device: Razer phone 2
 - OS: lineage microg 20
 - App version 2.2.0

**Additional context**

**Comment by yavko** [comment]
Update: seems to happen across albums too, just saves files in wrong places. Also downloading from songs not in my library also is happening

**Comment by Lambada10** [comment]
@yavko As per warning that displays before batch download
"This may be less accurate than downloading lyrics one by one"
This is because Spotify can return different songs, but are very similar (same title but different artist, same song but different version etc). This can't really be worked on

**Comment by yavko** [comment]
> @yavko As per warning that displays before batch download
> "This may be less accurate than downloading lyrics one by one"
> This is because Spotify can return different songs, but are very similar (same title but different artist, same song but different version etc). This can't really be worked on

Ah okay

**Comment by yavko** [comment]
> @yavko As per warning that displays before batch download
> "This may be less accurate than downloading lyrics one by one"
> This is because Spotify can return different songs, but are very similar (same title but different artist, same song but different version etc). This can't really be worked on

But that's just one of the issues

**Comment by yavko** [comment]
The other issue is that it downloads the right song, but saves in wrong place

**Comment by Lambada10** [comment]
Can I get more details about that? Never happened to me

**Comment by yavko** [comment]
> Can I get more details about that? Never happened to me

I ran the batch download and the right lyrics are  downloaded just under different songs, as shown in the screenshot. Sometimes same album, sometimes not

**Comment by Lambada10** [comment]
@yavko Probably also related to what Spotify returns

**Comment by yavko** [comment]
> @yavko Probably also related to what Spotify returns

Why is it like that? Maybe it'd be a better idea to use Musixmatch which I think Spotify uses

**Comment by Lambada10** [comment]
@yavko Musixmatch API is paid, and Spotify uses Musixmatch for lyrics either way

**Comment by yavko** [comment]
> @yavko Musixmatch API is paid, and Spotify uses Musixmatch for lyrics either way

I was able to use it for free, I used a cli tool to download lrcs from musixmatch

**Comment by yavko** [comment]
Yeah it's just downloading wrong songs, I've been manually doing it, and it's just how it is.
