### ISSUE TITLE
Possibility of Creating a Windows Version of SongSync App

### ISSUE THREAD

**Issue by peter9811** [Lambada10/SongSync#30]
I've been using your GitHub app, SongSync (https://github.com/Lambada10/SongSync), and I'm quite impressed with its features for managing music libraries and downloading lyrics.

I'd like to suggest the possibility of creating a Windows version of SongSync. Currently available for Android, the app's features could be really beneficial for Windows users as well. Many people use Windows for their music collections and having a dedicated app like SongSync would be great.

Expanding SongSync to Windows could have some key advantages:

Broader User Base: You'd tap into a new audience of Windows users looking for music management and lyric download solutions.

Consistency: Offering a consistent experience across different platforms can contribute to user loyalty.

Leveraging GitHub: Since the app is already on GitHub, development for the Windows version could happen right there, making it easier to collaborate and maintain.

Consider looking into the technical feasibility of adapting the app to run on Windows. If feasible, this could be a valuable addition to your project.

Thank you for considering this suggestion.

**Comment by NicholasFlamy** [comment]
Use lrcget
