### ISSUE TITLE
App Icon Not Visible

### ISSUE THREAD

**Issue by vibrantfix** [Lambada10/SongSync#33]
**Describe the bug**

App Icon Not Visible on the app menu .
**Smartphone (please complete the following information):**
- Device: Asus Zenfone Max pro m1
 - OS: Pixel Experience 10
 - App version : 2.2.0(220)

![Screenshot_20230825-105209_Trebuchet (1)](https://github.com/Lambada10/SongSync/assets/92950980/305b8193-ce48-44d7-bfef-cc5907c186dc)

**Comment by Lambada10** [comment]
@vibrantfix Any more details? Device? OS? Should work just fine

**Comment by vibrantfix** [comment]
Okay 👍

**Comment by DestroyerAce** [comment]
Facing the same issue but in:

- Device: Xiaomi redmi 9(Cattail)
- OS: MIUI 12.0.18 Global / Android 10
- App version : 2.2.0 

![IMG_20230911_021350](https://github.com/Lambada10/SongSync/assets/86879466/4bd2cfad-5387-4d9b-95be-f52bc4861283)
![Screenshot_2023-09-11-02-18-12-958_com android settings](https://github.com/Lambada10/SongSync/assets/86879466/76dd83b5-317f-42e8-ab3b-081c5555bf7f)

**Comment by FabiRich** [comment]
I had the same problem on my device with Android 10, I worked with my fix, which you can find here #37
