### ISSUE TITLE
an option to download translated lyrics

### ISSUE THREAD

**Issue by 5wHN28Dg** [Lambada10/SongSync#35]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Let's say the song is in Japanese so when I look for lyrics it would be awesome if there is an option to download for example the English lyrics (synced preferably)

**Describe alternatives you've considered**
The alternative would be me manually editing the lyrics and swapping it with the translated lyrics

**Additional context**
I believe apps like Musixmatch already offers multiple languages for the lyrics (if available)

**Comment by Lambada10** [comment]
@5wHN28Dg API I'm using doesn't return anything else than actual lyrics so it's most likely impossible to implement currently

**Comment by 5wHN28Dg** [comment]
Another suggestion then, I just downloaded the English lyrics for a Japanese song from a YT video but it is in SRT format so I'm currently editing the file manually line by line reformatting each line and then renaming the file to .lrc but this takes a lot of time so can you automate this in the app?
![Screenshot_20230904-125949_Editor](https://github.com/Lambada10/SongSync/assets/109148083/b16f3cc3-ffcf-4c44-8f7b-b0f305cc37d9)

**Comment by DestroyerAce** [comment]
I think adding "srt to lrc" to songsync wouldnt fit the goal of this project tbh

And just using chatgpt or some online tool to turn srt to lrc would solve your problem @5wHN28Dg

**Comment by 5wHN28Dg** [comment]
You are right
