### ISSUE TITLE
SpotifyLyricsAPI is no longer working.

### ISSUE THREAD

**Issue by PRinceBhai** [Lambada10/SongSync#38]
**Describe the bug**
Spotify changed something in their API which results in no lyric found by the app.

**To Reproduce**
Try any song.

**Expected behavior**
Lyric to show up and download.

**Screenshots**
Nope

**Smartphone (please complete the following information):**
 - Device: [Xiaomi Rendi Note 3]
 - OS: [ColtOS 6.7, Android 10]
 - App version [2.2.0]

**Additional context**
Someone posted a workaround on SpotifyLyricsAPI github issues. It involves reformatting the code to catch the token or something.

**Comment by Joeeeeb5** [comment]
+1

**Comment by Lambada10** [comment]
Fixed in 3879855
