### ISSUE TITLE
Swap Spotify API

### ISSUE THREAD

**Issue by Joeeeeb5** [Lambada10/SongSync#41]
**Is your feature request related to a problem? Please describe.**
Spotify is greedy and made lyrics a premium only feature 

**Describe the solution you'd like**
Switch the API to MusixMatch or Genius

**Comment by Lambada10** [comment]
@Joeeeeb5 Musixmatch:
Limited to 2k Daily API Calls 
Access to 30% of lyrics per song
https://developer.musixmatch.com/plans
Genius doesn't provide synced lyrics from what I know

You can look at the beta branch when I will add more lyrics sources and make the app use them later on

**Comment by Joeeeeb5** [comment]
> @Joeeeeb5 Musixmatch: Limited to 2k Daily API Calls Access to 30% of lyrics per song https://developer.musixmatch.com/plans Genius doesn't provide synced lyrics from what I know
> 
> You can look at the beta branch when I will add more lyrics sources and make the app use them later on

Darn it :( I'll keep an eye out for updates

**Comment by Paxsenix0** [comment]
> 
> Darn it :( I'll keep an eye out for updates

Hello:)) i'm newbie, and i have making php code to get synched lyrics from Musixmatch :))

https://github.com/Paxsenix0/MusixMatch-Lyrics

**Comment by Lambada10** [comment]
Fixed in 3879855, 707a6fe, 67571f0

**Comment by Lambada10** [comment]
First commit changes URL of Spotify lyrics API to working one, as developer of said API updated it. 2nd and 3rd commits add new lyrics providers
