### ISSUE TITLE
Error gettings lyrics

### ISSUE THREAD

**Issue by Berserk0001** [Lambada10/SongSync#42]
**Describe the bug**

**To Reproduce**
1. Go to 'Songsync app'
2. Click on '.search box'
3. Tye Song name:"Flower" and artist name: "Jisoo"
4. See error: No lyrics

**Expected behavior**
Lyrics are available.

**Screenshots**
![Screenshot_20231018-173855_Chrome](https://github.com/Lambada10/SongSync/assets/125671174/1679e887-3182-4019-b600-0be28246251f)

**Smartphone (please complete the following information):**
 - Device: [e.g. Samsung Galaxy S10, Poco X3 Pro]
 - OS: [e.g. MIUI 13 (Android 12), Pixel Experience 13]
 - App version [e.g. v1.3]

**Additional context**

**Comment by Lambada10** [comment]
Fixed in 3879855
