### ISSUE TITLE
LRC generator app suggestion

### ISSUE THREAD

**Issue by mizzunet** [Lambada10/SongSync#43]
This issue not for SongSync, but to suggest you an app to make because
* some songs in Spotify don't have synced lyrics(LRC)
* and currently SpotifyLyricsAPI broken anyway

Would you consider making a simple app that generates LRC out of lyrics plaintext? Something similar to https://github.com/DBKarman/lyricsync but as an app.

Here's how this works
* Enter lyrics
* Choose the song
* Now the song start playing
* Sync each lines as the singer sings
* An LRC generated in the end
* Pretty neat, isn't it?

Thanks

**Comment by Joeeeeb5** [comment]
already exists on playstore, it's called synced lyrics editor

**Comment by FabiRich** [comment]
This one is on fdroid and worked well for me [LRC Editor](https://www.f-droid.org/packages/com.cg.lrceditor/)
