### ISSUE TITLE
Crashing When Saving Lyrics

### ISSUE THREAD

**Issue by PlumBlossoms13** [Lambada10/SongSync#49]
**Describe the bug**
When choosing to save the lrc file, the app crashes

**To Reproduce**
Search for a song and choose to save the .lrc file

**Expected behavior**
It should save the file to my songs folder, the same folder that my music files are stored in

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Motorola G Stylus (2021)/ moto g stylus (XT2115DL)
 - OS: Android 11
 - App version: 3.0.0

**Additional context**
The app worked perfectly for the first three or so songs I tried to use. I'm using the Spotify provider. This happens when using the app installed straight from GitHub and from F-Droid

Edit: I noticed that this behavior only happens when I search for the song directly through the browse tab. If I choose the song from the home tab, it works

**Comment by NA0341** [comment]
Same here.

@PlumBlossoms13
I found out that you need to **set the SDCard location first for the save function to work.**
It saves the file in the Music folder (both internal & external storage work).


**Additional info:**

I'm on SAMSUNG Android 9 (OneUI v. 1.0) with Kernel 4.4.111 (2022-07-25). It's the stock EU ROM.
Device is Samsung Galaxy S8 (SM-G950F).

SongSync v. 4.0.0 (newest).


Copy function works fine, on save it crashes instantly.

**There should be a check function which opens the file picker dialog if the storage location wasn't previously set!**
