### ISSUE TITLE
Won't start

### ISSUE THREAD

**Issue by iJahangard** [Lambada10/SongSync#5]
I'm using Android 13 Custom ROM
Installed the app but it will crash immediately after i run it

**Comment by Lambada10** [comment]
Please send logcat

**Comment by BobbyESP** [comment]
If it is just at start is probably something related to the permissions

**Comment by iJahangard** [comment]
Gaved permissions but .....
Anyway i guess it was about something else cuz the app work after a while

**Comment by iJahangard** [comment]
> Please send logcat

Here is the log
[2023-06-29-12-12-59.txt](https://github.com/Lambada10/SongSync/files/11903773/2023-06-29-12-12-59.txt)

**Comment by iJahangard** [comment]
> Gaved permissions but .....
Anyway i guess it was about something else cuz the app work after a while

It starts crashing again

**Comment by Lambada10** [comment]
> Here is the log [2023-06-29-12-12-59.txt](https://github.com/Lambada10/SongSync/files/11903773/2023-06-29-12-12-59.txt)

` java.io.FileNotFoundException: https://accounts.spotify.com/api/token`

If it was due to no internet connection, it would've thrown UnknownHostException
Is Spotify working fine in your country?

**Comment by iJahangard** [comment]
No Spotify won't be accessible without VPN since my country is under embargo by Spotify

Anyway app should show me "connection failed" message, not crashing with no information
