### ISSUE TITLE
[major] crashing issue

### ISSUE THREAD

**Issue by Joeeeeb5** [Lambada10/SongSync#51]
**Describe the bug**
When I exclude folders from the search and reopen the app, it crashes and refuses to launch until I clear data.

**To Reproduce**
exactly what was described

**Expected behavior**
App opens

**Smartphone (please complete the following information):**
 - Device: Poco M3
 - OS: MIUI 14 (Android 12)
 - App version: 3.0.0

**Comment by NicholasFlamy** [comment]
Very similar problem, except that the app opens afterwards with whichever folder I tried to exclude which caused it to crash unexcluded.
