### ISSUE TITLE
Adding mxlrc to this app (using musixmatch library)

### ISSUE THREAD

**Issue by Taki132** [Lambada10/SongSync#56]
I think it helpful for me to fetch some vietnamese song 

Link:https://github.com/fashni/MxLRC

**Comment by Lambada10** [comment]
@Taki132 Spotify uses lyrics from Musixmatch so technically speaking it's already implemented

**Comment by Taki132** [comment]
> @Taki132 Spotify uses lyrics from Musixmatch so technically speaking it's already implemented

Okay.
In my opinion some song not in spotify (but it on musixmatch) for example: die alone (Hoaprox)
![Screenshot_20240324_234144_Musixmatch.png](https://github.![Screenshot_20240324_234205_Spotify.png](https://github.com/Lambada10/SongSync/assets/92381976/88e1fe8f-f1ff-4e62-a4d0-bf1e1dbec245)

-97d1-5fcfe27ca081)

![Screenshot_20240324_234205_Spotify.png](https://github.com/Lambada10/SongSync/assets/92381976/27f29dd7-a8e7-4ea1-b2f4-e71f4e3ad3aa)



Bonus song on spotify showed but songsync not found:
![Screenshot_20240324_234308_Spotify.png](https://github.com/Lambada10/SongSync/assets/92381976/dd44b27f-7d9b-4847-b451-ec5be69efeae)

![Screenshot_20240324_233954_SongSync.png](https://github.com/Lambada10/SongSync/assets/92381976/88766438-7917-4b21-ae04-16d2a73b8cdb)
