### ISSUE TITLE
Crashes when switching to home 

### ISSUE THREAD

**Issue by Turhvjbufv** [Lambada10/SongSync#57]
**Describe the bug**
Crashes when returning to home page after saving lyrics from search for lyrics song
**To Reproduce**
Press any song, search for lyrics with him and save lyrics then press on home button
**Expected behavior**
Should return to home and show you all other songs
**Screenshots**

**Smartphone (please complete the following information):**
 - Device: A72
 - OS: lineage os a13
 - App version 3.0.1

**Additional context**
Crash logs ![crash-pl-lambada-songsync-21_02-09-00-56_896.zip](https://github.com/Lambada10/SongSync/files/14355585/crash-pl-lambada-songsync-21_02-09-00-56_896.zip)

**Comment by Lambada10** [comment]
@Turhvjbufv Does this happen every time, I can't reproduce it

**Comment by Lambada10** [comment]
@Turhvjbufv I'll close this for now, feel free to re-open if needed
