### ISSUE TITLE
Option to turn off moving text

### ISSUE THREAD

**Issue by NikunjKhangwal** [Lambada10/SongSync#62]
This could significantly improve the performance, specially in low-end devices.

**Comment by okgamr** [comment]
What do you mean by "moving text"?
Is it the synced lyrics, or the animations in the app?
Btw, there's no performance issue with synced lyrics, so you're probably talking about the animations, which are provided by the SDK, not the code. Unfortunately, there's no way to disable these, but you can't try to remove the animations from the device settings (requires developer settings; info and tutorials about it on Google) and i guess it includes the animations within apps (the custom animations in the code won't be removed though, but those that are provided by the SDK will)
Tell me if it works or it's something else

**Comment by NikunjKhangwal** [comment]
I was talking about the animations in the app. The moving texts of song names specifically. Developer options works system-wide not for single app right?

**Comment by okgamr** [comment]
Yes, you're right, dev settings are systemwide and may be not pleasant to look at. I've seen an app that had the option to turn off animations, but I forgot its name. If I remember it I'll comment here

**Comment by NikunjKhangwal** [comment]
Ok. Thank you
