### ISSUE TITLE
Internal error when using LRCLib

### ISSUE THREAD

**Issue by satoon10** [Lambada10/SongSync#65]
**Describe the bug**
LCRLib gives error when using.
**To Reproduce**
Steps to reproduce the behavior;
1. Select LCRLib as source;
2. Try to fetch lyrics for any song.
3. See error

**Expected behavior**
SongSync should be able to get lyrics without giving an error.

**Screenshots**
![Screenshot_20240502-045121_SongSync](https://github.com/Lambada10/SongSync/assets/60121690/47c34bb6-bac6-4935-abf1-4c268083df34)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy Note 8
 - OS: Android 10
 - App version: 3.0.2

**Comment by llinek** [comment]
I'm currently experiencing the same error,
I'm using Huawei P20 on Android 10 and EMUI 12, app version is 3.0.2.
I think this issue is more relevant as Spotify currently limited lyrics to its premium users, and the Netease option doesn't work as well.

**Comment by okgamr** [comment]
Same error here
