### ISSUE TITLE
No Internet Connection Error

### ISSUE THREAD

**Issue by aayushmishra01** [Lambada10/SongSync#76]
Suddenly from today the app has stopped working, it is saying - No Internet Connection,
![Screenshot_2024-08-03-18-58-54-555_pl lambada songsync](https://github.com/user-attachments/assets/f329fed8-827a-4834-be94-ca26d042bc0d)

**Comment by aayushmishra01** [comment]
Perfectly working now 🤸🏻‍♂️

**Comment by PytatoDuck** [comment]
I just downloaded this app (first time opening it), and I'm facing the same thing. How did you fix it, or did it get fixed automatically?
