### ISSUE TITLE
The ability to encode lyrics into the song file, instead of saving a .lrc file

### ISSUE THREAD

**Issue by u12bdragon** [Lambada10/SongSync#79]
I am frustrated when I have to save a .lrc file instead of embedding it into the actual song file, therefore adding more visual clutter to my file system and making sure I have to transfer more files when I move my music library.

**Describe the solution you'd like**
The solution would be to have an option to imbed the lyrics into the song file instead of saving them as a lyric file.

**Describe alternatives you've considered**
 The only alternative is the current behavior which is to save a lyric file

**Additional context**
Other apps have this option but do not even search for synced lyrics in the first place

**Comment by Lambada10** [comment]
It's being worked on ( #78 )
