### ISSUE TITLE
Ignore .nomedia

### ISSUE THREAD

**Issue by lalalasupa0** [Lambada10/SongSync#87]
**Is your feature request related to a problem? Please describe.**
I guess, it doesn't load music located in folders with a .nomedia file

**Describe the solution you'd like**
For the app to detect the music even with the .nomedia file in there, like what the usual music players do (e.j. Poweramp, Namida)

**Describe alternatives you've considered**
_In **additional context**_

**Additional context**
I create a .nomedia file because I want the cover.jpg that I have in the same folder as the music to not be visible in my gallery. I know that simply placing the cover.jpg + .nomedia in an individual folder inside the same folder where the music is would solve this, but I wanted to make the request anyway because I think it would save that little bit of work

**Comment by Lambada10** [comment]
@lalalasupa0 Mediastore default behavior, won't fix

**Comment by lalalasupa0** [comment]
@Lambada10 I think I got an issue related to this... In any case, I just want confirmation of my assumption
I got music files in ~storage/Music/folder1/folder2/album, but I has a .nomedia in `/album` that I deleted before going into SongSync to check for lyrics, but it doesn't appear there

The thing is, I got other albums in similar paths, do you think there were *somehow* remants of the .nomedia file, or something of the like, that makes SongSync ignore it?

**Comment by nift4** [comment]
@lalalasupa0 try rebooting your device

**Comment by ecogice** [comment]
I think that using .nomedia for music folders that contain album art is practically required if you don't want your gallery to be filled with them. any folder that contains the .nomedia file will not be shown in the filters, though apps like Poweramp still have access to the music files without using any special permissions. This makes the app useless for me sadly

**Comment by nift4** [comment]
@ecogice .nomedia means "all media files are to be ignored", and as explained before mediastore enforces that ignoring and we can't unignore it without scanning all music file tags ourselves (Poweramp does that). It's not only a "ignore photos" toggle as unfortunate as that is.
