### ISSUE TITLE
To be able to choose other lyrics in a provider

### ISSUE THREAD

**Issue by lalalasupa0** [Lambada10/SongSync#89]
**Is your feature request related to a problem? Please describe.**
It's annoying when the app chooses the first option from LRCLib by default, this because that one tend to have sync errors

**Describe the solution you'd like**
To be able to choose other lyrics from a same privider (LRCLib)

**Describe alternatives you've considered**
Going to the LRCLib website and doing everything manually, but that has disadvantages

**Additional context**
Example of what I said first: https://lrclib.net/search/future%20swag%20young%20thug — The app chooses the first option, but that one has quite a lot of synchronizing problems meanwhile the 2nd is perfect (imo)

**Comment by nift4** [comment]
@lalalasupa0 Have you tried the "Try again" button? It should do basically that

**Comment by lalalasupa0** [comment]
> @lalalasupa0 Have you tried the "Try again" button? It should do basically that

![Screenshot_20241006_010411_SongSync](https://github.com/user-attachments/assets/9768c434-6f5a-43e9-9cb9-bf09e4181991)

The try again button comes up like this for me, every time. So I would say no

**Comment by nift4** [comment]
Hmm, my bad, I thought that works for lrclib as well

**Comment by BobbyESP** [comment]
No, the problem seems to be that LrcLib retrieves always no lyrics. The "Try again" button would do that explained job, but the problem is that the provider seems to be broken
