### ISSUE TITLE
Timecode change

### ISSUE THREAD

**Issue by Anonuser-01** [Lambada10/SongSync#90]
**Is your feature request related to a problem? Please describe.**

I sometimes download songs from YouTube and it tends to have some non song audio, such as extra long music or other audio. This causes the time synced lyrics downloaded from SongSync to not match up.

**Describe the solution you'd like**

Allow to adjust the synced lyrics time codes by adding or subtracting when the lyrics are played. 

**Describe alternatives you've considered**

N/A

**Additional context**

Implementation would be similar to some video players with subtitle support that allow adjusting the time codes to line up with the film audio.

![image](https://github.com/user-attachments/assets/bb734d10-51d0-4f13-b675-81bf851290ef)

**Comment by Lambada10** [comment]
Hi,

I assume you mean to set the offset on the specific song screen, as it wouldn't make sense on batch downloads. 
Could you test if this works as intended?

https://github.com/Lambada10/SongSync/actions/runs/11383707236/artifacts/2068387473

**Comment by Anonuser-01** [comment]
Hi, yes I meant on the song screen. This looks nice, and I can change the offset in the app, but the time does not show in the lyrics within the app and also when I export it as lrc. 

Also, as you can see in the image, I had to offset by several seconds which takes time to do with the .1 offset so it would be nice to see a 1 second offset next to the .1 offset. You'll probably have to shrink the .1 button a bit to add the 1 second next to it. What could also work is if I can hold on the .1 offset button and it changes quick instead of having to press it for each change.

![image](https://github.com/user-attachments/assets/c1874aca-57da-43df-a429-75d0fe01a690)


Thanks!

**Comment by Lambada10** [comment]
The timestamp does not change as there's dedicated offset LRC tag.
https://en.m.wikipedia.org/wiki/LRC_(file_format)#File_format

**Comment by Anonuser-01** [comment]
Oh interesting. Didn't know that! Unfortunately I have tried it with several players and none of them seem to support the offset tag. 

I guess it's not a standard according to the article you shared: 

"ID tags may optionally appear before the lyrics,[2] although some players may not recognize or simply ignore this" 

Are you able to make it so when I change the offset, it changes the time codes by that amount? I don't think it would be that difficult to implement because if the time add is 10 seconds, you would just need to add 10 seconds to all the timecodes.

Thanks
