### ISSUE TITLE
Embed non synced lyrics

### ISSUE THREAD

**Issue by Anonuser-01** [Lambada10/SongSync#91]
**Is your feature request related to a problem? Please describe.**

Embedded lyrics can't be used for synced lyrics by _many_ music players. This results in lyrics being displayed with the timecodes.

**Describe the solution you'd like**

Please add support for embedding lyrics without timecodes / regular lyrics.

**Describe alternatives you've considered**

Inserting lyrics manually

**Additional context**

N/A

**Comment by Anonuser-01** [comment]
LRCLib.net supports synced lyrics and regular lyrics

https://lrclib.net/

![Screenshot_20241019_080556](https://github.com/user-attachments/assets/60b76a2e-3851-407a-a16e-b211746db3fe)

**Comment by kingmadwik** [comment]
Musicolet, Poweramp, Symphony (foss droid) these all support time synced lyrics and they are a great addition to normal lyrics
