### ISSUE TITLE
Edit Lyrics in App

### ISSUE THREAD

**Issue by Anonuser-01** [Lambada10/SongSync#96]
**Is your feature request related to a problem? Please describe.**

Unable to edit lyrics.

**Describe the solution you'd like**

Allow editing lyrics in the app so I can add my own details to the lyrics such as comments.

**Describe alternatives you've considered**

Open up lyrics in text editor

**Additional context**

https://en.m.wikipedia.org/wiki/LRC_(file_format)

![Screenshot_20241023_155441_SongSync.jpg](https://github.com/user-attachments/assets/3db09d5a-ca29-4ab9-9032-ef2c9fc107fd)

**Comment by nxoim** [comment]
Hi there. The feature is unlikely to be added as it doesn't fit the scope of the app. The app is meant to provide lyrics from web services. Please refer to text/lyrics editor apps
