### ISSUE TITLE
Filter songs that already has lyrics, isnt working

### ISSUE THREAD

**Issue by kingmadwik** [Lambada10/SongSync#97]
**Describe the bug**
This feature wasnt working for me from many releases. I tried changing options to see if anything was causing problems but nothing worked

![Screenshot_2024-10-24-01-43-24-41_372870d89fd5f8ba7a994f975f281c90](https://github.com/user-attachments/assets/f72a17ff-a4c9-4dbf-999e-4e1fd8f9744b)

i have lyrics for most songs but it still include them in the list of non-lyrics songs

**Comment by kingmadwik** [comment]
Okay lyrics detection worksfor embedded lyrics or only .LRC files only ?

**Comment by Lambada10** [comment]
@kingmadwik Current impl looks for a LRC file named the same as song file to check if it has lyrics already

**Comment by kingmadwik** [comment]
@Lambada10 then this isnt a bug at all, im sorry for wasting your time.  Maybe you can consider adding a feature that checks for embedded lyrics and then show them in the no lyrics section. thanks for the app till now.

**Comment by kerollosy** [comment]
> @Lambada10 then this isnt a bug at all, im sorry for wasting your time. Maybe you can consider adding a feature that checks for embedded lyrics and then show them in the no lyrics section. thanks for the app

I can work on this if lambada isn't already

**Comment by bugreporter005** [comment]
Any updates on that?

**Comment by kerollosy** [comment]
It seems the only way to check if a song has embedded lyrics is to read the entire metadata of the song using TagLib, but unfortunately this process can be quite slow and would cause a significant delay in loading the app

**Comment by kingmadwik** [comment]
> It seems the only way to check if a song has embedded lyrics is to read the entire metadata of the song using TagLib, but unfortunately this process can be quite slow and would cause a significant delay in loading the app

Ohk then maybe untill we find out better way to do this, its not worth it. Thanks for the reply.
